### ISSUE TITLE
Facebook conversions don't pass correct currency

### ISSUE THREAD

**Issue by albybarber** [segment-integrations/analytics.js-integration-facebook-conversion-tracking#1]
I have been testing using analytics.js and have noticed that conversions with currency are not being tracked properly.

I know what the fix is but can't get `npm test` to work? do i need a particular version of node or npm?

**Comment by sperand-io** [comment]
@albybarber thanks for flagging this! the `package.json` should specify the required toolchain in devDeps. I know this is tangential from addressing your specific issue, but we want to make sure these repos are self-contained and testable without any obstacles, so would you mind sharing the error you're seeing and the version of node you're running?

If you can explain the specific issue you're seeing wrt currency we're happy to help with the fix, as well! Thanks!

**Comment by albybarber** [comment]
Thanks for the rapid response @sperand-io 

I have created a pull request for the fix (ignore the first one something happen to the tabbing)

I am happy to switch versions of node or npm.

I am currently on `node - v4.2.2` and `npm - 3.3.12`

I get this error after an `npm install`

```
npm WARN ENOENT ENOENT: no such file or directory, open '/Users/alby/gitCode/analytics.js-integration-facebook-conversion-tracking/node_modules/combine-source-map/package.json'
npm WARN EPEERINVALID eslint-config-segment@1.0.18 requires a peer of eslint-plugin-react@^2.3.0 but none was installed.
```

When I run `npm test`
![cursor_and_1__bash_and_facebook_conversions_don_t_pass_correct_currency_ _issue__1_ _segment-integrations_analytics_js-integration-facebook-conversion-tracking](https://cloud.githubusercontent.com/assets/462491/11100864/8ba4a516-8868-11e5-9f14-6c022d79a18f.png)

```
node: bad option: --harmony-generators
make: *** [test-phantomjs] Error 9
npm ERR! Test failed.  See above for more details.
```

**Comment by sperand-io** [comment]
@albybarber thanks! damn yea, looks like something funky going on with `duo-test` for node >4. I think the CLI tool is passing that flag automatically — perhaps @yields @stevenmatheison @dominicbarnes or @ndhoule could weigh in on that :grin: 

Could you try running on `0.12` :cry: 

We'll get this addressed ASAP!

**Comment by albybarber** [comment]
@sperand-io That seems to get it working!! Thanks.
I still get sauce lab errors but i think they are less important, see

![cursor_and_1__bash](https://cloud.githubusercontent.com/assets/462491/11102663/bca56e5c-8872-11e5-9519-20e7913d0ec1.png)

**Comment by hankim813** [comment]
This integration has been deprecated in favor of [Facebook Pixel](https://segment.com/docs/integrations/facebook-pixel/)

**Comment by f2prateek** [comment]
@hankim813 if that's the case, let's boneyard this repo?

**Comment by hankim813** [comment]
@f2prateek yeah not sure what the state of deprecation regarding this repo is. @sperand-io did all the migration so I'm sure he can confirm
